apiVersion: v1
kind: Service
metadata:
  name: docker-registryui
  labels:
    app: docker-registryui
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 5001
    name: docker-registryui
    protocol: TCP
    targetPort: 5001 #Docker Registry App required port
    nodePort: 30043 #It can be changed optionally 
  - port: 7681
    name: docker-registryui-terminal  #Terminal name
    protocol: TCP
    targetPort: 7681 #Terminal requried port
    nodePort: 30443 #It can be changed optionally.
  selector:
    app: docker-registryui #Deployment selector name
